release: alembic upgrade head
web: gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --preload
worker: celery -A app.celery_app.celery_app worker -l info --concurrency=1
